permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author: 
  name: 徐源
  email: web_xy@126.com
  link: http://webxy.cn
  weibo: http://weibo.com/webxy
  github: http://github.com/webxy

# 站点信息
title: 徐源的博客
description: 徐源的博客
url: http://webxy.cn
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/photo.jpg
favicon: /public/img/photo.jpg

# google analytics 设置
ga:
  id: UA-54767140-1
  url: webxy.cn

# disqus 设置
disqus:
  shortname: web_xy

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Python
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
